In [78]:
import pandas as pd
from dataset import get_power_consumption, get_oil_weekly_prices
import plotly.express as px
import plotly.graph_objects as go

# DATA_1: Basel Energy Demand

In [79]:
df1 = get_power_consumption()

In [67]:
df1.head(20)

                           consumptions(kWh)
time
2011-12-31 23:00:00+00:00       33266.801667
2012-01-01 00:00:00+00:00       32576.005625
2012-01-01 01:00:00+00:00       31332.701250
2012-01-01 02:00:00+00:00       30217.414375
2012-01-01 03:00:00+00:00       29454.123750
2012-01-01 04:00:00+00:00       29875.141250
2012-01-01 05:00:00+00:00       30469.248750
2012-01-01 06:00:00+00:00       31244.613750
2012-01-01 07:00:00+00:00       31838.418750
2012-01-01 08:00:00+00:00       32416.274375
2012-01-01 09:00:00+00:00       34011.998125
2012-01-01 10:00:00+00:00       35210.738750
2012-01-01 11:00:00+00:00       36134.710625
2012-01-01 12:00:00+00:00       36826.679375
2012-01-01 13:00:00+00:00       36990.436875
2012-01-01 14:00:00+00:00       37072.685625
2012-01-01 15:00:00+00:00       37737.496250
2012-01-01 16:00:00+00:00       40494.276250
2012-01-01 17:00:00+00:00       42201.961875
2012-01-01 18:00:00+00:00       41710.955625

## Reflection on the DATA_1 generation process:

#### Data collection process:
    SOURCE: From electricty usage meters and how much electricty was put into the grid
    INTERVAL: 15 minutes
    RANGE: 30.12.2011 - 15.09.2025

### Visualization
#### Time plot

In [20]:
fig = px.line(df1.resample('h').mean(), title='Basel Energy Demand in Kwh ')
fig.show()

In [77]:
pivot_df.head(10)

Week                  1             2             3             4
DayOfWeek
0          45395.750286  48850.864141  49737.919896  49223.851198
1          47446.983958  49458.588490  49969.299792  49518.051641
2          48086.147396  49704.756693  50545.001406  49733.164583
3          48931.931094  49916.592135  51666.704036  50064.099323
4          48634.734219  49840.032031  51208.161510  49921.937865
5          41632.155417  42357.367786  43221.430495  42135.206406
6          37501.237448  38024.654948  38043.927370  38364.186589

### Visualization
#### Seasonal plot
 - weekly pattern behavior(speculation, checking through a seasonal plot). We select the jan month of the time series

In [41]:
df1 = df1.resample('h').mean()
df1_jan_month = df1.iloc[1:720, :]
fig = px.line(df1_jan_month, title='Basel Energy Demand in Kwh  in the month of JANUARY')
fig.show()

In [74]:
df = df1_jan_month.copy()

df['DayOfWeek'] = df.index.dayofweek
df['Week'] = df.index.isocalendar().week

pivot_df = df.pivot_table(index='DayOfWeek', columns='Week',
                           values='consumptions(kWh)', aggfunc='mean')
pivot_df.dropna(axis = 1, inplace = True)


# Plot each week
fig = go.Figure()
day_names = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

for week in pivot_df.columns:
    fig.add_trace(go.Scatter(
        x=day_names,
        y=pivot_df[week],
        mode='lines+markers',
        name=f'Week {week}'
    ))

fig.update_layout(
    title='Seasonal Plot: Weekly Consumption Pattern',
    xaxis_title='Day of Week',
    yaxis_title='Consumption (kWh)',
    hovermode='x unified'
)

fig.show()

## Factors Influencing the data
- seasons(e.g. winter and summer) affect the magnitude of consumption levels.
- The downward trend in the consumption magnitude could be because the energy efficiency through electrical grid got better

## Expected patterns
- Downward trend in energy cosumption
- seasonal behavior with multiple frequencies: day/night, weekly, yearly

# DATA_2: Crude Oil Prices: West Texas Intermediate (WTI) - Cushing, Oklahoma

### Reflection on the data2 generation process:

#### Data collection process:
    SOURCE: U.S. Energy Information Administration
    INTERVAL: Weekly
    RANGE: 1986-01-02 - 2025-12-15

In [81]:
df2 = get_oil_weekly_prices()

In [84]:
df2.head(n=10)

            closing
date
1986-01-03    26.00
1986-01-10    25.65
1986-01-17    23.63
1986-01-24    19.45
1986-01-31    18.95
1986-02-07    17.70
1986-02-14    16.03
1986-02-21    13.63
1986-02-28    13.23
1986-03-07    12.24

### Visualization
#### Time plot

In [85]:
fig = px.line(df2, title='Oil Price in Dollars per Barrel')
fig.show()

# Review of Notebook
Review notebooks of Modern Time Series Forecasting with Python – Chapter 2 (GitHub repository)
https://github.com/PacktPublishing/Modern-Time-Series-Forecasting-with-Python/tree/main/notebooks/Chapter02

Load and visualize datasets with Python.
Analysis:
- Explain and interpret the plots. How noisy is the data?

Due to the small interval and large range the visualization is very noisy.
Therefore seaonal and daily cycles are not really visibly.
The predicted trend towards less energy consumption due to solar power over the years is visible.

- Review patterns, do they match your expectations given your understanding of the DGP?

The general nosiyness was expected due to the large number of data points.

Large range of values as well, due to the small interval measuring the change of demand which changes by the minute.

- Review outliers, interpret them, and match with corresponding real-world events when applicable

There is a big dip in may 2020, which corresponds with the COVID19 pandemic. Due to everyone having to isolate a lot less energy was needed.